"""alert lights fixes

Revision ID: 021c8fb64b1a
Revises: cdf46d1d224f
Create Date: 2025-06-18 21:18:45.908701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021c8fb64b1a'
down_revision = 'cdf46d1d224f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.drop_column('dew_point')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('dew_point', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
