"""baseline

Revision ID: 23ddd62d7e64
Revises: 
Create Date: 2025-06-05 23:25:38.736200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ddd62d7e64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_sn', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_sn'),
    schema='sonde'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='sonde'
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mission_number', sa.String(length=50), nullable=False),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('mask', sa.String(), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sonde.devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sonde.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_number'),
    schema='sonde'
    )
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('alarm_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['sonde.flights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sonde'
    )
    op.create_table('flight_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('measurement_age', sa.Integer(), nullable=True),
    sa.Column('transmission_age', sa.Integer(), nullable=True),
    sa.Column('flight_phase', sa.String(length=20), nullable=True),
    sa.Column('burst_detected', sa.Boolean(), nullable=True),
    sa.Column('burst_altitude', sa.Float(), nullable=True),
    sa.Column('current_ascent_rate', sa.Float(), nullable=True),
    sa.Column('max_altitude', sa.Float(), nullable=True),
    sa.Column('min_pressure', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['sonde.flights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id'),
    schema='sonde'
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['sonde.flights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sonde'
    )
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_altitude', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('ascent_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['sonde.flights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sonde'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry', schema='sonde')
    op.drop_table('logs', schema='sonde')
    op.drop_table('flight_status', schema='sonde')
    op.drop_table('alarms', schema='sonde')
    op.drop_table('flights', schema='sonde')
    op.drop_table('users', schema='sonde')
    op.drop_table('devices', schema='sonde')
    # ### end Alembic commands ###
