"""Add release_ts to flight_status

Revision ID: 32c21a926f31
Revises: ad8b3c2d77d7
Create Date: 2025-06-09 10:42:16.154840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c21a926f31'
down_revision = 'ad8b3c2d77d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('release_ts', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.drop_column('release_ts')

    # ### end Alembic commands ###
