"""Add gps performance to telemetry

Revision ID: 600a1978c803
Revises: ffae2fcfb4b3
Create Date: 2025-06-11 16:34:28.212526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600a1978c803'
down_revision = 'ffae2fcfb4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('hdop', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sats', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.drop_column('sats')
        batch_op.drop_column('hdop')

    # ### end Alembic commands ###
