"""Add humidity to telemetry

Revision ID: 7981a3d09efe
Revises: 985ed59d5feb
Create Date: 2025-06-10 16:36:04.904902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7981a3d09efe'
down_revision = '985ed59d5feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('humidity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.drop_column('humidity')

    # ### end Alembic commands ###
