"""Add end_ts to flight_status

Revision ID: 985ed59d5feb
Revises: 32c21a926f31
Create Date: 2025-06-09 11:56:14.931775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985ed59d5feb'
down_revision = '32c21a926f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('end_ts', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.drop_column('end_ts')

    # ### end Alembic commands ###
