"""Add GroundReference table

Revision ID: ad8b3c2d77d7
Revises: 1f9a7956a6a5
Create Date: 2025-06-06 13:10:46.377655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad8b3c2d77d7'
down_revision = '1f9a7956a6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_altitude', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('api_temperature', sa.Float(), nullable=True),
    sa.Column('api_pressure', sa.Float(), nullable=True),
    sa.Column('api_humidity', sa.Float(), nullable=True),
    sa.Column('api_location_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['sonde.flights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id'),
    schema='sonde'
    )
    with op.batch_alter_table('devices', schema='sonde') as batch_op:
        batch_op.alter_column('device_sn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('flights', schema='sonde') as batch_op:
        batch_op.alter_column('mask',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('tx_ts')
        batch_op.drop_column('humidity')
        batch_op.drop_column('measurement_ts')
        batch_op.drop_column('processed_ts')
        batch_op.drop_column('sats')
        batch_op.drop_column('device_sn')
        batch_op.drop_column('hdop')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('hdop', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_sn', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sats', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('processed_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('measurement_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tx_ts', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('flights', schema='sonde') as batch_op:
        batch_op.alter_column('mask',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('devices', schema='sonde') as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('device_sn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.drop_table('ground_reference', schema='sonde')
    # ### end Alembic commands ###
