"""emoji cols added2

Revision ID: c440d0280e78
Revises: 74a1dbf6d9fd
Create Date: 2025-06-18 14:53:21.313052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c440d0280e78'
down_revision = '74a1dbf6d9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('release_altitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.drop_column('release_altitude')

    # ### end Alembic commands ###
