"""Add level field to logs

Revision ID: c46c7ffa41db
Revises: 7981a3d09efe
Create Date: 2025-06-10 16:59:16.778048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46c7ffa41db'
down_revision = '7981a3d09efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema='sonde') as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
