"""alert lights added

Revision ID: cdf46d1d224f
Revises: c440d0280e78
Create Date: 2025-06-18 20:51:38.019743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf46d1d224f'
down_revision = 'c440d0280e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('receiver_ok', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parser_ok', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sensor_ok', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('signal_level', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('packet_ok', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('age_warn', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('calibrated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('temp_low', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_degrad', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gps_fix', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gps_degrad', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.drop_column('gps_degrad')
        batch_op.drop_column('gps_fix')
        batch_op.drop_column('data_degrad')
        batch_op.drop_column('temp_low')
        batch_op.drop_column('calibrated')
        batch_op.drop_column('age_warn')
        batch_op.drop_column('packet_ok')
        batch_op.drop_column('signal_level')
        batch_op.drop_column('sensor_ok')
        batch_op.drop_column('parser_ok')
        batch_op.drop_column('receiver_ok')

    # ### end Alembic commands ###
