"""Add anchor_ts to flight_status

Revision ID: ffae2fcfb4b3
Revises: c46c7ffa41db
Create Date: 2025-06-11 16:11:47.051621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffae2fcfb4b3'
down_revision = 'c46c7ffa41db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('anchor_ts', sa.DateTime(), nullable=True))

    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.add_column(sa.Column('tx_ts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_ts', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('measurement_ts', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema='sonde') as batch_op:
        batch_op.drop_column('measurement_ts')
        batch_op.drop_column('processed_ts')
        batch_op.drop_column('tx_ts')

    with op.batch_alter_table('flight_status', schema='sonde') as batch_op:
        batch_op.drop_column('anchor_ts')

    # ### end Alembic commands ###
